Feature: Email Alerts
  In order to keep up with the latest news on a site
  As a user of the site
  I want to be able to receive alerts

  Scenario: Subscribe to alerts
    Given I have a project with alerts configured
    And I am logged into the site as a normal user
    When I visit "/account/edit/alerts/"
    And I choose "All Alerts" be sent timed as "Immediately"
    And an alert is generated by the system
    Then I should receive that alert

  Scenario: Subscribe to delayed alerts (before)
    Given I have a project with alerts configured
    And I am logged into the site as a normal user
    When I select "All Alerts" be sent timed as "Midday Digest"
    And an alert is generated by the system
    Then I should not receive that alert

  Scenario: Receiving delayed alerts
    Given I have a project with alerts configured
    And I am logged into the site as a normal user
    When I select "All Alerts" be sent timed as "Midday Digest"
    And an alert is generated by the system
    And the "Midday Digest" alerts are sent
    Then I should receive that alert

  Scenario: Category specific alerts
    Given I have a project with alerts configured
    And I am a user receiving "Sports" alerts "Immediately"
    When an alert is generated for an article in the "Sports" section
    Then I should receive that alert

  Scenario: No alerts received outside category
    Given I have a project with alerts configured
    And I am a user receiving "Sports" alerts "Immediately"
    When an alert is generated for an article in the "Arts" section
    Then I should not receive that alert

  Scenario: Category specific alerts in digests
    Given I have a project with alerts configured
    And I am a user receiving "Sports" alerts "Midday Digest"
    When an alert is generated for an article in the "Sports" section
    Then I should not receive that alert

  Scenario: Category specific alerts in digests
    Given I have a project with alerts configured
    And I am a user receiving "Sports" alerts "Midday Digest"
    When an alert is generated for an article in the "Sports" section
    And the "Midday Digest" alerts are sent
    Then I should receive that alert
